{% set name = "quadpy" %}
{% set version = "0.16.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/quadpy-{{ version }}.tar.gz
  sha256: 60f7152f0e62a369989be3e176a6d9bb3e9bc696d5ba101c1a8eecffb4ed1482

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >3.5
  run:
    - importlib-metadata
    - ndim
    - numpy
    - orthopy <0.10,>=0.9
    - python >3.5
    - scipy
    - sympy

test:
  imports:
    - quadpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nschloe/quadpy
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Numerical integration (quadrature, cubature) in Python
  description: |
    Your one-stop shop for numerical integration in Python.
  doc_url: https://github.com/nschloe/quadpy
  dev_url: https://github.com/nschloe/quadpy

extra:
  recipe-maintainers:
    - jan-janssen
