schema_version: 1

context:
  name: quadpy
  version: "0.16.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/quadpy-${{ version }}.tar.gz
  sha256: 6915dd2cbb3bf3980168e81dff8cc11c91e5f045edf7ee95011d1c8af79acfd1

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >3.5
  run:
    - importlib-metadata
    - ndim
    - numpy
    - orthopy <0.10,>=0.9
    - python >3.5
    - scipy
    - sympy

tests:
  - python:
      imports:
        - quadpy
      pip_check: true

      python_version: ${{ python_min }}.*
about:
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Numerical integration (quadrature, cubature) in Python
  description: |
    Your one-stop shop for numerical integration in Python.
  homepage: https://github.com/nschloe/quadpy
  repository: https://github.com/nschloe/quadpy
  documentation: https://github.com/nschloe/quadpy

extra:
  recipe-maintainers:
    - jan-janssen
